// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: edge/v1/edge.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Edge_CheckBlacklistAddress_FullMethodName = "/api.edge.v1.Edge/CheckBlacklistAddress"
)

// EdgeClient is the client API for Edge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EdgeClient interface {
	// 检查地址是否在黑名单中
	CheckBlacklistAddress(ctx context.Context, in *CheckBlacklistAddressRequest, opts ...grpc.CallOption) (*CheckBlacklistAddressResponse, error)
}

type edgeClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeClient(cc grpc.ClientConnInterface) EdgeClient {
	return &edgeClient{cc}
}

func (c *edgeClient) CheckBlacklistAddress(ctx context.Context, in *CheckBlacklistAddressRequest, opts ...grpc.CallOption) (*CheckBlacklistAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBlacklistAddressResponse)
	err := c.cc.Invoke(ctx, Edge_CheckBlacklistAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeServer is the server API for Edge service.
// All implementations must embed UnimplementedEdgeServer
// for forward compatibility.
type EdgeServer interface {
	// 检查地址是否在黑名单中
	CheckBlacklistAddress(context.Context, *CheckBlacklistAddressRequest) (*CheckBlacklistAddressResponse, error)
	mustEmbedUnimplementedEdgeServer()
}

// UnimplementedEdgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeServer struct{}

func (UnimplementedEdgeServer) CheckBlacklistAddress(context.Context, *CheckBlacklistAddressRequest) (*CheckBlacklistAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBlacklistAddress not implemented")
}
func (UnimplementedEdgeServer) mustEmbedUnimplementedEdgeServer() {}
func (UnimplementedEdgeServer) testEmbeddedByValue()              {}

// UnsafeEdgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeServer will
// result in compilation errors.
type UnsafeEdgeServer interface {
	mustEmbedUnimplementedEdgeServer()
}

func RegisterEdgeServer(s grpc.ServiceRegistrar, srv EdgeServer) {
	// If the following call pancis, it indicates UnimplementedEdgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Edge_ServiceDesc, srv)
}

func _Edge_CheckBlacklistAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBlacklistAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServer).CheckBlacklistAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Edge_CheckBlacklistAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServer).CheckBlacklistAddress(ctx, req.(*CheckBlacklistAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Edge_ServiceDesc is the grpc.ServiceDesc for Edge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Edge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.edge.v1.Edge",
	HandlerType: (*EdgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckBlacklistAddress",
			Handler:    _Edge_CheckBlacklistAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edge/v1/edge.proto",
}
