// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: limit/v1/limit.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLimitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainName     string                 `protobuf:"bytes,1,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`          // 链名称
	UserAddress   string                 `protobuf:"bytes,2,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`    // 用户地址
	TokenAddress  string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"` // 代币地址
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`                               // 数量
	Direction     int32                  `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`                          // 方向 1: 买入 2: 卖出
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`                                 // 价格
	GasPrice      float64                `protobuf:"fixed64,7,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`           //gas 价格
	Symbol        string                 `protobuf:"bytes,8,opt,name=symbol,proto3" json:"symbol,omitempty"`                                 // 交易符号 BNB/USDT
	StorageId     string                 `protobuf:"bytes,9,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`          // 存储ID
	Slippage      float64                `protobuf:"fixed64,10,opt,name=slippage,proto3" json:"slippage,omitempty"`                          // 滑点
	FeePercent    float64                `protobuf:"fixed64,11,opt,name=fee_percent,json=feePercent,proto3" json:"fee_percent,omitempty"`    // 手续费百分比
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLimitOrderRequest) Reset() {
	*x = CreateLimitOrderRequest{}
	mi := &file_limit_v1_limit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLimitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLimitOrderRequest) ProtoMessage() {}

func (x *CreateLimitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limit_v1_limit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLimitOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateLimitOrderRequest) Descriptor() ([]byte, []int) {
	return file_limit_v1_limit_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLimitOrderRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *CreateLimitOrderRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *CreateLimitOrderRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *CreateLimitOrderRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateLimitOrderRequest) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *CreateLimitOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateLimitOrderRequest) GetGasPrice() float64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *CreateLimitOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateLimitOrderRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *CreateLimitOrderRequest) GetSlippage() float64 {
	if x != nil {
		return x.Slippage
	}
	return 0
}

func (x *CreateLimitOrderRequest) GetFeePercent() float64 {
	if x != nil {
		return x.FeePercent
	}
	return 0
}

type CreateLimitOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLimitOrderReply) Reset() {
	*x = CreateLimitOrderReply{}
	mi := &file_limit_v1_limit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLimitOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLimitOrderReply) ProtoMessage() {}

func (x *CreateLimitOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_limit_v1_limit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLimitOrderReply.ProtoReflect.Descriptor instead.
func (*CreateLimitOrderReply) Descriptor() ([]byte, []int) {
	return file_limit_v1_limit_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLimitOrderReply) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelLimitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelLimitOrderRequest) Reset() {
	*x = CancelLimitOrderRequest{}
	mi := &file_limit_v1_limit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLimitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLimitOrderRequest) ProtoMessage() {}

func (x *CancelLimitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limit_v1_limit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLimitOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelLimitOrderRequest) Descriptor() ([]byte, []int) {
	return file_limit_v1_limit_proto_rawDescGZIP(), []int{2}
}

func (x *CancelLimitOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelLimitOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelLimitOrderReply) Reset() {
	*x = CancelLimitOrderReply{}
	mi := &file_limit_v1_limit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLimitOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLimitOrderReply) ProtoMessage() {}

func (x *CancelLimitOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_limit_v1_limit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLimitOrderReply.ProtoReflect.Descriptor instead.
func (*CancelLimitOrderReply) Descriptor() ([]byte, []int) {
	return file_limit_v1_limit_proto_rawDescGZIP(), []int{3}
}

var File_limit_v1_limit_proto protoreflect.FileDescriptor

const file_limit_v1_limit_proto_rawDesc = "" +
	"\n" +
	"\x14limit/v1/limit.proto\x12\fapi.limit.v1\"\xdd\x02\n" +
	"\x17CreateLimitOrderRequest\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x01 \x01(\tR\tchainName\x12!\n" +
	"\fuser_address\x18\x02 \x01(\tR\vuserAddress\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\x05R\tdirection\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1b\n" +
	"\tgas_price\x18\a \x01(\x01R\bgasPrice\x12\x16\n" +
	"\x06symbol\x18\b \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"storage_id\x18\t \x01(\tR\tstorageId\x12\x1a\n" +
	"\bslippage\x18\n" +
	" \x01(\x01R\bslippage\x12\x1f\n" +
	"\vfee_percent\x18\v \x01(\x01R\n" +
	"feePercent\"2\n" +
	"\x15CreateLimitOrderReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"4\n" +
	"\x17CancelLimitOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x17\n" +
	"\x15CancelLimitOrderReply2\xc7\x01\n" +
	"\x05Limit\x12^\n" +
	"\x10CreateLimitOrder\x12%.api.limit.v1.CreateLimitOrderRequest\x1a#.api.limit.v1.CreateLimitOrderReply\x12^\n" +
	"\x10CancelLimitOrder\x12%.api.limit.v1.CancelLimitOrderRequest\x1a#.api.limit.v1.CancelLimitOrderReplyB8\n" +
	"\fapi.limit.v1P\x01Z&corn_trade_backend_rpc/api/limit/v1;v1b\x06proto3"

var (
	file_limit_v1_limit_proto_rawDescOnce sync.Once
	file_limit_v1_limit_proto_rawDescData []byte
)

func file_limit_v1_limit_proto_rawDescGZIP() []byte {
	file_limit_v1_limit_proto_rawDescOnce.Do(func() {
		file_limit_v1_limit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_limit_v1_limit_proto_rawDesc), len(file_limit_v1_limit_proto_rawDesc)))
	})
	return file_limit_v1_limit_proto_rawDescData
}

var file_limit_v1_limit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_limit_v1_limit_proto_goTypes = []any{
	(*CreateLimitOrderRequest)(nil), // 0: api.limit.v1.CreateLimitOrderRequest
	(*CreateLimitOrderReply)(nil),   // 1: api.limit.v1.CreateLimitOrderReply
	(*CancelLimitOrderRequest)(nil), // 2: api.limit.v1.CancelLimitOrderRequest
	(*CancelLimitOrderReply)(nil),   // 3: api.limit.v1.CancelLimitOrderReply
}
var file_limit_v1_limit_proto_depIdxs = []int32{
	0, // 0: api.limit.v1.Limit.CreateLimitOrder:input_type -> api.limit.v1.CreateLimitOrderRequest
	2, // 1: api.limit.v1.Limit.CancelLimitOrder:input_type -> api.limit.v1.CancelLimitOrderRequest
	1, // 2: api.limit.v1.Limit.CreateLimitOrder:output_type -> api.limit.v1.CreateLimitOrderReply
	3, // 3: api.limit.v1.Limit.CancelLimitOrder:output_type -> api.limit.v1.CancelLimitOrderReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_limit_v1_limit_proto_init() }
func file_limit_v1_limit_proto_init() {
	if File_limit_v1_limit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_limit_v1_limit_proto_rawDesc), len(file_limit_v1_limit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_limit_v1_limit_proto_goTypes,
		DependencyIndexes: file_limit_v1_limit_proto_depIdxs,
		MessageInfos:      file_limit_v1_limit_proto_msgTypes,
	}.Build()
	File_limit_v1_limit_proto = out.File
	file_limit_v1_limit_proto_goTypes = nil
	file_limit_v1_limit_proto_depIdxs = nil
}
